In [1]:
!pip install -U fsds_100719
from fsds_100719.imports import *

import nba_stats as ns

fsds_1007219  v0.6.1 loaded.  Read the docs: https://fsds.readthedocs.io/en/latest/

In [2]:
ids = pd.read_csv('data/nba_fd_ids.csv')

# for col in ['NB]
ids = ids.fillna(0)

float_cols = ids.select_dtypes(float).columns
ids[float_cols] = ids[float_cols].astype(int)
ids

    TEAM                     PLAYER   FD_ID   NBA_ID
0    OKC              Adams, Steven   23169   203500
1    MIA               Adebayo, Bam   80817  1628389
2     SA         Aldridge, LaMarcus    9688   200746
3     NO  Alexander-Walker, Nickeil  110356  1629638
4    MEM             Allen, Grayson   84711  1628960
..   ...                        ...     ...      ...
505  CHI            Young, Thaddeus    9666   201152
506  ATL                Young, Trae   84671  1629027
507  CHA               Zeller, Cody   15691   203469
508  CLE                Zizic, Ante   70824  1627790
509  LAC               Zubac, Ivica   70827  1627826

[510 rows x 4 columns]

In [3]:
fd_to_nba_ids = dict(zip(ids['FD_ID'],ids['NBA_ID']))
fd_to_nba_ids

{23169: 203500,
 80817: 1628389,
 9688: 200746,
 110356: 1629638,
 84711: 1628960,
 80821: 1628386,
 58289: 1628443,
 12342: 202329,
 23716: 203937,
 9772: 201583,
 40199: 203507,
 84725: 1628961,
 111372: 203648,
 9508: 2546,
 68090: 1628384,
 23740: 1627853,
 9538: 2772,
 9466: 201571,
 84673: 1629028,
 66061: 1628407,
 84679: 1628963,
 80806: 1628366,
 84675: 1628964,
 9495: 200826,
 15946: 203084,
 110357: 1629628,
 17333: 203115,
 84688: 1628966,
 9809: 201587,
 37931: 203382,
 19781: 203145,
 110637: 1629647,
 15595: 203078,
 66064: 1627736,
 9715: 201158,
 40769: 1628395,
 49336: 1627761,
 70819: 1627733,
 14543: 202722,
 12474: 201976,
 16081: 203920,
 110359: 1629048,
 14505: 202687,
 12368: 202357,
 12355: 202339,
 55060: 203992,
 14530: 202711,
 110313: 1629626,
 58574: 1628413,
 110311: 1629648,
 84722: 1629067,
 58460: 1626164,
 68203: 1628449,
 110829: 1628968,
 111671: 1629065,
 12334: 202340,
 80823: 1628396,
 110308: 1629714,
 110335: 1629649,
 84670: 1628969,
 84678: 1628970,
 117283: 1629052,
 84833: 1629151,
 16359: 1627763,
 60233: 1628415,
 84694: 1628971,
 117290: 1629718,
 67026: 1627759,
 117286: 1629650,
 40262: 1628425,
 84668: 1628972,
 84690: 1628973,
 67312: 1628418,
 15947: 203493,
 15843: 203504,
 14510: 202692,
 85106: 1629126,
 14528: 202710,
 55058: 203998,
 0: 202322,
 15636: 203484,
 117285: 1628427,
 55059: 203991,
 9787: 201960,
 84696: 1628975,
 9654: 1713,
 84676: 1628976,
 16201: 203487,
 23981: 1627936,
 23823: 1626161,
 9473: 2199,
 9636: 201163,
 117305: 1629597,
 97018: 1629185,
 67707: 1627737,
 101331: 1629109,
 110353: 1629634,
 20640: 203903,
 110354: 1629651,
 110909: 1629598,
 48583: 1628499,
 111492: 1629599,
 66236: 1628381,
 80815: 1628380,
 9575: 201144,
 15993: 1626192,
 15582: 1626188,
 115994: 1629076,
 12362: 202326,
 20491: 203496,
 15501: 203459,
 20277: 1628470,
 15800: 203109,
 110333: 1629633,
 15583: 203552,
 9524: 201939,
 20805: 203584,
 15755: 203076,
 12365: 202334,
 116340: 1629056,
 9714: 201942,
 16301: 203473,
 20064: 203521,
 84681: 1628978,
 66091: 1627767,
 84699: 1628977,
 15771: 203476,
 15542: 203915,
 84669: 1629029,
 111273: 1629652,
 23676: 1628422,
 110639: 1629635,
 66196: 1628408,
 9673: 201609,
 15557: 203083,
 9677: 201162,
 23802: 1627739,
 110332: 1629035,
 66455: 1627740,
 9956: 201961,
 49111: 203954,
 17491: 203516,
 97263: 1629234,
 84697: 1628980,
 55055: 203957,
 112710: 1629605,
 12351: 202324,
 63478: 1626245,
 80820: 1628390,
 110329: 1628981,
 23772: 1627812,
 16376: 1627827,
 23788: 1627854,
 23096: 203095,
 80810: 1628368,
 117287: 1629606,
 84720: 1628982,
 23589: 1626187,
 16071: 204025,
 80805: 1628365,
 85466: 1629117,
 110325: 1629655,
 9637: 201568,
 17230: 204038,
 110342: 1629636,
 9581: 201188,
 9570: 0,
 9577: 200752,
 12341: 202331,
 9481: 201959,
 80819: 1628385,
 84680: 1628983,
 40203: 203497,
 96763: 1629164,
 41594: 203932,
 9556: 201569,
 84706: 1628984,
 20806: 1626203,
 23831: 203924,
 82697: 1627982,
 9758: 201980,
 15860: 203110,
 9849: 101123,
 15405: 203210,
 112709: 1629750,
 9648: 201145,
 9560: 201933,
 113306: 1629741,
 110358: 1629657,
 110349: 1629060,
 84684: 1628985,
 15846: 203501,
 9644: 201935,
 16178: 203090,
 117819: 1629607,
 23776: 1626149,
 24544: 203914,
 16363: 203925,
 14518: 202699,
 82744: 1627885,
 40562: 1628404,
 80825: 1628392,
 9589: 2617,
 110340: 1629637,
 12366: 202330,
 15952: 203089,
 110307: 1629608,
 70822: 1627823,
 63127: 1626195,
 110312: 1629639,
 63123: 1626209,
 23665: 1627741,
 9703: 201588,
 15417: 203524,
 115802: 1629658,
 84719: 1628988,
 9663: 201950,
 16604: 203200,
 42148: 1626178,
 23447: 1626158,
 15904: 203918,
 9453: 201143,
 110337: 1629659,
 23294: 1627863,
 9660: 2730,
 84704: 1628989,
 110338: 1629631,
 84707: 1628990,
 9957: 201586,
 9664: 2738,
 9598: 101141,
 59318: 204060,
 66048: 1627742,
 14498: 202681,
 80811: 1628371,
 48940: 1628411,
 80824: 1628402,
 84683: 1628991,
 80809: 1628367,
 58134: 1628382,
 14523: 202704,
 110334: 1629713,
 9488: 2544,
 23581: 1628518,
 117307: 1629610,
 110331: 1629660,
 84718: 1628993,
 101327: 1629168,
 110316: 1629661,
 9966: 201949,
 110347: 1629640,
 58350: 1626169,
 18600: 204020,
 55062: 203999,
 41082: 1627745,
 66968: 1627884,
 58081: 1626145,
 9561: 201599,
 14529: 202709,
 110355: 1629662,
 16448: 1626163,
 14516: 202683,
 66046: 1628379,
 111835: 1629742,
 15758: 203077,
 117297: 1629663,
 81621: 1628467,
 14506: 202688,
 84674: 1628995,
 111376: 1629723,
 70826: 1627788,
 41083: 1628436,
 9870: 2594,
 84700: 1629066,
 58377: 1628398,
 40783: 203897,
 66109: 1627746,
 15559: 203087,
 110321: 1629641,
 23780: 1627774,
 23798: 1627747,
 80818: 1628388,
 116202: 1629665,
 9615: 201584,
 18376: 1627814,
 15814: 203458,
 14513: 202695,
 15669: 203086,
 20848: 203081,
 110343: 1629642,
 58576: 1626172,
 9621: 201572,
 9873: 201577,
 9874: 201567,
 9535: 200768,
 70825: 1627789,
 58461: 1626168,
 85309: 1629133,
 74163: 203705,
 9953: 101133,
 70820: 1627748,
 110315: 1629611,
 63826: 1626246,
 80812: 1628374,
 113267: 1628997,
 110351: 1628998,
 115612: 1629103,
 49114: 1628412,
 111622: 1629726,
 9799: 202083,
 58658: 1627775,
 19067: 203468,
 18393: 204456,
 110350: 1629667,
 18256: 203926,
 9739: 201580,
 15744: 203585,
 18435: 1628035,
 85597: 1629162,
 15727: 203463,
 16230: 203895,
 110697: 1629740,
 84703: 1629001,
 84701: 1629002,
 16261: 203114,
 9725: 101139,
 15762: 203121,
 18811: 1626259,
 9939: 201988,
 9729: 200794,
 84691: 1629003,
 66113: 1628378,
 23155: 1628513,
 110882: 1629690,
 80816: 1628370,
 14554: 202734,
 110344: 1629630,
 117289: 1629752,
 14512: 202694,
 14511: 202693,
 40396: 1628420,
 41597: 1628405,
 63124: 1626144,
 67708: 1627749,
 66108: 1627750,
 84698: 1629058,
 17894: 203488,
 84713: 1629004,
 19726: 1627846,
 20992: 1626204,
 15560: 203894,
 9512: 2403,
 40208: 203526,
 23156: 1627777,
 23825: 203457,
 111470: 1629668,
 110317: 1629669,
 80813: 1628373,
 101329: 1629134,
 42733: 1628021,
 18338: 1626220,
 17384: 203124,
 48598: 1628400,
 58083: 1626143,
 84686: 1629059,
 84689: 1629006,
 110309: 1629644,
 15684: 203506,
 22541: 203482,
 110324: 1629671,
 63126: 1626224,
 58153: 1626162,
 42550: 203953,
 14537: 202718,
 110323: 1629672,
 12340: 202335,
 66424: 1628383,
 9623: 101108,
 19138: 203901,
 96775: 203658,
 85521: 1629033,
 15590: 203486,
 58378: 1627751,
 110881: 1629738,
 110910: 1629044,
 110322: 1629673,
 110345: 1629645,
 84682: 1629008,
 15628: 203490,
 42156: 1626171,
 63122: 204001,
 16196: 203939,
 16293: 1626181,
 23572: 1627752,
 67025: 1628397,
 42669: 203944,
 113305: 1629729,
 110339: 1629629,
 9655: 200755,
 110995: 1629675,
 101266: 1629244,
 16233: 1626196,
 15592: 203085,
 15548: 203460,
 85137: 1629130,
 23800: 203922,
 84677: 1629010,
 111371: 1629620,
 84709: 1629011,
 110346: 1629676,
 9455: 200765,
 9475: 201565,
 16405: 203082,
 42677: 1626179,
 14496: 201937,
 58312: 1626156,
 59358: 1627734,
 110640: 1629677,
 16183: 203960,
 55056: 203967,
 23097: 203107,
 110328: 1629678,
 40201: 203471,
 16368: 203118,
 9647: 200757,
 84667: 1629012,
 84724: 1629013,
 110330: 1629621,
 14515: 202697,
 60021: 1627783,
 117274: 1629735,
 66115: 1627732,
 81623: 1628424,
 84717: 1629014,
 110365: 1629346,
 23670: 203935,
 80814: 1628372,
 12511: 202397,
 84672: 1629015,
 17517: 203503,
 84705: 1629016,
 112708: 1629622,
 58270: 1628410,
 66185: 1628403,
 80808: 1628369,
 9446: 201952,
 11074: 202066,
 81529: 1628464,
 14559: 202738,
 84723: 1629017,
 110827: 1629744,
 14501: 202684,
 110320: 1629680,
 9920: 201229,
 58462: 1626157,
 84695: 1629018,
 84827: 1629019,
 23407: 200782,
 12359: 202323,
 58253: 1626167,
 14503: 202685,
 24546: 1627756,
 24247: 1627832,
 84721: 1629020,
 42661: 203943,
 14514: 202696,
 110883: 1629731,
 84714: 1629021,
 16220: 203079,
 14507: 202689,
 84702: 1629022,
 24186: 1627820,
 40561: 1628476,
 16790: 202954,
 23120: 203933,
 110352: 1629023,
 85238: 1629139,
 110319: 1629682,
 110348: 1629683,
 9642: 201566,
 110326: 1629632,
 49675: 1628401,
 12363: 202355,
 49116: 203952,
 110318: 1629684,
 85305: 1629026,
 9662: 101150,
 9451: 101107,
 84708: 1629057,
 111620: 1628430,
 110310: 1629627,
 58295: 1628391,
 110341: 1629685,
 58084: 1626159,
 42202: 1626174,
 40830: 1626153,
 110327: 1629625,
 9666: 201152,
 84671: 1629027,
 15691: 203469,
 70824: 1627790,
 70827: 1627826}

## Loading in a competition

In [4]:
pd.set_option('display.max_columns',0)
pd.set_option('display.max_rows',100)

In [5]:
df = pd.read_csv('data/AFTER-HOURS-MULTI-FanDuel-NBA-2019-12-28-42127-players-list.csv')
df

              Id Position  First Name  ... Tier Unnamed: 14  Unnamed: 15
0    42127-15755       PF     Anthony  ...  NaN         NaN          NaN
1     42127-9488       SF      LeBron  ...  NaN         NaN          NaN
2    42127-14513       PF       Kawhi  ...  NaN         NaN          NaN
3    42127-20848       PG      Damian  ...  NaN         NaN          NaN
4    42127-40203        C        Rudy  ...  NaN         NaN          NaN
5    42127-12363        C      Hassan  ...  NaN         NaN          NaN
6    42127-66113       SG     Donovan  ...  NaN         NaN          NaN
7    42127-12341       SF        Paul  ...  NaN         NaN          NaN
8    42127-19067       SG          CJ  ...  NaN         NaN          NaN
9     42127-9508       SF     Carmelo  ...  NaN         NaN          NaN
10   42127-14530       SF       Bojan  ...  NaN         NaN          NaN
11   42127-59318       SF         Joe  ...  NaN         NaN          NaN
12   42127-23776        C    Montrezl  ...  NaN         NaN          NaN
13    42127-9662       SG         Lou  ...  NaN         NaN          NaN
14   42127-58377       PF        Kyle  ...  NaN         NaN          NaN
15   42127-12474       PG     Patrick  ...  NaN         NaN          NaN
16   42127-20640       SG      Jordan  ...  NaN         NaN          NaN
17    42127-9575       PG        Mike  ...  NaN         NaN          NaN
18   42127-19781       SF        Kent  ...  NaN         NaN          NaN
19    42127-9455       PG       Rajon  ...  NaN         NaN          NaN
20    42127-9739        C      JaVale  ...  NaN         NaN          NaN
21   42127-15636       SG  Kentavious  ...  NaN         NaN          NaN
22   42127-18338       PF       Royce  ...  NaN         NaN          NaN
23   42127-70827        C       Ivica  ...  NaN         NaN          NaN
24    42127-9660        C      Dwight  ...  NaN         NaN          NaN
25   42127-66109       PF        Skal  ...  NaN         NaN          NaN
26   42127-63124       PG    Emmanuel  ...  NaN         NaN          NaN
27    42127-9758       SG       Danny  ...  NaN         NaN          NaN
28   42127-16178       SF     Maurice  ...  NaN         NaN          NaN
29   42127-23981       PG        Alex  ...  NaN         NaN          NaN
30   42127-84724       PG      Landry  ...  NaN         NaN          NaN
31   42127-15744       SG      Rodney  ...  NaN         NaN          NaN
32  42127-110337       SG       Talen  ...  NaN         NaN          NaN
33  42127-111492       PF        Amir  ...  NaN         NaN          NaN
34  42127-111620       PG       Nigel  ...  NaN         NaN          NaN
35  42127-110343       SF      Nassir  ...  NaN         NaN          NaN
36  42127-110355       SF     Mfiondu  ...  NaN         NaN          NaN
37   42127-63123       SF       Mario  ...  NaN         NaN          NaN
38   42127-15904       SF      Rodney  ...  NaN         NaN          NaN
39  42127-117286        C       Moses  ...  NaN         NaN          NaN
40  42127-117289       PF       Juwan  ...  NaN         NaN          NaN
41   42127-15405       PF    JaMychal  ...  NaN         NaN          NaN
42   42127-12334       SG       Avery  ...  NaN         NaN          NaN
43   42127-80815       PF        Zach  ...  NaN         NaN          NaN
44   42127-12340       PF     Patrick  ...  NaN         NaN          NaN
45  42127-117301       PF    Devontae  ...  NaN         NaN          NaN
46   42127-80823        C        Tony  ...  NaN         NaN          NaN
47    42127-9920       PF     Anthony  ...  NaN         NaN          NaN
48   42127-84677       PG      Jerome  ...  NaN         NaN          NaN
49   42127-20805       SG        Troy  ...  NaN         NaN          NaN
50   42127-12362        C    DeMarcus  ...  NaN         NaN          NaN
51    42127-9677       SF       Jared  ...  NaN         NaN          NaN
52   42127-12365       PF          Ed  ...  NaN         NaN          NaN
53  42127-116178       PG      Rayjon  ...  NaN         NaN          NaN
54   42127-84695       SG        Gary  ...  NaN         NaN          NaN
55  42127-115802       SF      Jaylen  ...  NaN         NaN          NaN
56   42127-15582       PG       Quinn  ...  NaN         NaN          NaN
57  42127-110308       SF     Jarrell  ...  NaN         NaN          NaN
58  42127-110315       SG     Terance  ...  NaN         NaN          NaN
59   42127-84717       PG    Anfernee  ...  NaN         NaN          NaN
60   42127-40561       PG     Derrick  ...  NaN         NaN          NaN
61   42127-23156       PF     Georges  ...  NaN         NaN          NaN
62   42127-84725       PF      Kostas  ...  NaN         NaN          NaN
63  42127-110324       SG        Miye  ...  NaN         NaN          NaN
64  42127-110327       PG      Justin  ...  NaN         NaN          NaN
65   42127-41597       PF   Johnathan  ...  NaN         NaN          NaN

[66 rows x 16 columns]

## FETCHING PLAYER DATA

In [6]:
fd_ids = df['Id'].apply(lambda x: int(x.split('-')[-1].strip())).copy()
fd_ids

0      15755
1       9488
2      14513
3      20848
4      40203
5      12363
6      66113
7      12341
8      19067
9       9508
10     14530
11     59318
12     23776
13      9662
14     58377
15     12474
16     20640
17      9575
18     19781
19      9455
20      9739
21     15636
22     18338
23     70827
24      9660
25     66109
26     63124
27      9758
28     16178
29     23981
30     84724
31     15744
32    110337
33    111492
34    111620
35    110343
36    110355
37     63123
38     15904
39    117286
40    117289
41     15405
42     12334
43     80815
44     12340
45    117301
46     80823
47      9920
48     84677
49     20805
50     12362
51      9677
52     12365
53    116178
54     84695
55    115802
56     15582
57    110308
58    110315
59     84717
60     40561
61     23156
62     84725
63    110324
64    110327
65     41597
Name: Id, dtype: int64

In [7]:
fd_ids[0]

15755

In [8]:
nba_ids = fd_ids.map(fd_to_nba_ids)
nba_ids

0      203076.0
1        2544.0
2      202695.0
3      203081.0
4      203497.0
5      202355.0
6     1628378.0
7      202331.0
8      203468.0
9        2546.0
10     202711.0
11     204060.0
12    1626149.0
13     101150.0
14    1628398.0
15     201976.0
16     203903.0
17     201144.0
18     203145.0
19     200765.0
20     201580.0
21     203484.0
22    1626220.0
23    1627826.0
24       2730.0
25    1627746.0
26    1626144.0
27     201980.0
28     203090.0
29    1627936.0
30    1629013.0
31     203585.0
32    1629659.0
33    1629599.0
34    1628430.0
35    1629642.0
36    1629662.0
37    1626209.0
38     203918.0
39    1629650.0
40    1629752.0
41     203210.0
42     202340.0
43    1628380.0
44     202335.0
45          NaN
46    1628396.0
47     201229.0
48    1629010.0
49     203584.0
50     202326.0
51     201162.0
52     202334.0
53          NaN
54    1629018.0
55    1629658.0
56    1626188.0
57    1629714.0
58    1629611.0
59    1629014.0
60    1628476.0
61    1627777.0
62    1628961.0
63    1629671.0
64    1629625.0
65    1628405.0
Name: Id, dtype: float64

In [9]:
## THESE PLAYERS ARE MISSING A MATCH
df[nba_ids.isna()]

              Id Position First Name  ... Tier Unnamed: 14  Unnamed: 15
45  42127-117301       PF   Devontae  ...  NaN         NaN          NaN
53  42127-116178       PG     Rayjon  ...  NaN         NaN          NaN

[2 rows x 16 columns]

In [10]:
df['nba_id'] = nba_ids.copy()
df = df.dropna(subset=['nba_id'])
df['nba_id'] = df['nba_id'].astype(int)
df

//anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

              Id Position  First Name  ... Unnamed: 14 Unnamed: 15   nba_id
0    42127-15755       PF     Anthony  ...         NaN         NaN   203076
1     42127-9488       SF      LeBron  ...         NaN         NaN     2544
2    42127-14513       PF       Kawhi  ...         NaN         NaN   202695
3    42127-20848       PG      Damian  ...         NaN         NaN   203081
4    42127-40203        C        Rudy  ...         NaN         NaN   203497
5    42127-12363        C      Hassan  ...         NaN         NaN   202355
6    42127-66113       SG     Donovan  ...         NaN         NaN  1628378
7    42127-12341       SF        Paul  ...         NaN         NaN   202331
8    42127-19067       SG          CJ  ...         NaN         NaN   203468
9     42127-9508       SF     Carmelo  ...         NaN         NaN     2546
10   42127-14530       SF       Bojan  ...         NaN         NaN   202711
11   42127-59318       SF         Joe  ...         NaN         NaN   204060
12   42127-23776        C    Montrezl  ...         NaN         NaN  1626149
13    42127-9662       SG         Lou  ...         NaN         NaN   101150
14   42127-58377       PF        Kyle  ...         NaN         NaN  1628398
15   42127-12474       PG     Patrick  ...         NaN         NaN   201976
16   42127-20640       SG      Jordan  ...         NaN         NaN   203903
17    42127-9575       PG        Mike  ...         NaN         NaN   201144
18   42127-19781       SF        Kent  ...         NaN         NaN   203145
19    42127-9455       PG       Rajon  ...         NaN         NaN   200765
20    42127-9739        C      JaVale  ...         NaN         NaN   201580
21   42127-15636       SG  Kentavious  ...         NaN         NaN   203484
22   42127-18338       PF       Royce  ...         NaN         NaN  1626220
23   42127-70827        C       Ivica  ...         NaN         NaN  1627826
24    42127-9660        C      Dwight  ...         NaN         NaN     2730
25   42127-66109       PF        Skal  ...         NaN         NaN  1627746
26   42127-63124       PG    Emmanuel  ...         NaN         NaN  1626144
27    42127-9758       SG       Danny  ...         NaN         NaN   201980
28   42127-16178       SF     Maurice  ...         NaN         NaN   203090
29   42127-23981       PG        Alex  ...         NaN         NaN  1627936
30   42127-84724       PG      Landry  ...         NaN         NaN  1629013
31   42127-15744       SG      Rodney  ...         NaN         NaN   203585
32  42127-110337       SG       Talen  ...         NaN         NaN  1629659
33  42127-111492       PF        Amir  ...         NaN         NaN  1629599
34  42127-111620       PG       Nigel  ...         NaN         NaN  1628430
35  42127-110343       SF      Nassir  ...         NaN         NaN  1629642
36  42127-110355       SF     Mfiondu  ...         NaN         NaN  1629662
37   42127-63123       SF       Mario  ...         NaN         NaN  1626209
38   42127-15904       SF      Rodney  ...         NaN         NaN   203918
39  42127-117286        C       Moses  ...         NaN         NaN  1629650
40  42127-117289       PF       Juwan  ...         NaN         NaN  1629752
41   42127-15405       PF    JaMychal  ...         NaN         NaN   203210
42   42127-12334       SG       Avery  ...         NaN         NaN   202340
43   42127-80815       PF        Zach  ...         NaN         NaN  1628380
44   42127-12340       PF     Patrick  ...         NaN         NaN   202335
46   42127-80823        C        Tony  ...         NaN         NaN  1628396
47    42127-9920       PF     Anthony  ...         NaN         NaN   201229
48   42127-84677       PG      Jerome  ...         NaN         NaN  1629010
49   42127-20805       SG        Troy  ...         NaN         NaN   203584
50   42127-12362        C    DeMarcus  ...         NaN         NaN   202326
51    42127-9677       SF       Jared  ...         NaN         NaN   201162
52   42127-12365       PF          Ed  ...         NaN         NaN   202334
54   42127-84695       SG        Gary  ...         NaN         NaN  1629018
55  42127-115802       SF      Jaylen  ...         NaN         NaN  1629658
56   42127-15582       PG       Quinn  ...         NaN         NaN  1626188
57  42127-110308       SF     Jarrell  ...         NaN         NaN  1629714
58  42127-110315       SG     Terance  ...         NaN         NaN  1629611
59   42127-84717       PG    Anfernee  ...         NaN         NaN  1629014
60   42127-40561       PG     Derrick  ...         NaN         NaN  1628476
61   42127-23156       PF     Georges  ...         NaN         NaN  1627777
62   42127-84725       PF      Kostas  ...         NaN         NaN  1628961
63  42127-110324       SG        Miye  ...         NaN         NaN  1629671
64  42127-110327       PG      Justin  ...         NaN         NaN  1629625
65   42127-41597       PF   Johnathan  ...         NaN         NaN  1628405

[64 rows x 17 columns]

### Loop to scrape player data

In [11]:
help(ns)

Help on module nba_stats:

NAME
    nba_stats

FUNCTIONS
    calc_fantasy_stats(df, pts=None)
        Calculates FantasyPoints from corresponding data columns.

        Args:
            df (Frame): df produced by get_all_seasons_df or get_season_df

        Returns:
            df_fantasy (Frane): original df + additional fantasy points columns

    get_all_seasons_df(season_urls=None, player_id=None, season_years=[2019, 2018, 2017])
        Extract data from all season urls provided and concatenate into one dataframe.
        Args:
            season_urls (list of str, optional): List of urls to extract from. If None, generate season_urls from player_id.
            player_id (str or int, optional): stats.nba.com player_id for urls. Defaults to None.
            season_years (list, optional): [description]. Defaults to [2019,2018,2017].

        Raises:
            Exception: Must provided EITHER list of season_urls
                or player_id & season_years to generate them with `make_season_urls_from_playerid`

        Returns:
            df_combined (Frame): df with all seasons for provided urls/player_id

    get_season_df(url, driver=None)
        Loads the provided url. Intended for: stats.nba.com/player/{player_id}}/boxscores-traditional/)
        Helper Function to `get_all_seasons_df`, but can be used alone.
        Args:
            url (str): nba stats plaer boxscore-traditional page.
            driver (Chrome webdrive), optional): Selenium webdriver object. Created if not provided. Defaults to None.

        Returns:
            df (Frame): extracted data table from stats.nba.com

    make_season_urls_from_playerid(player_id='1628369', season_years=[2019, 2018, 2017])
        Creates the correct urls for each of the season years programmatically.
        base_url = f"https://stats.nba.com/player/{player_id}/boxscores-traditional/"
        season_suffix = f"?Season={start_YR}-{end_yr}&SeasonType=Regular%20Season"

        Args:
            player_id (str, optional): stats.nba.com player id for url. Defaults to '1628369'.
            season_years (list of ints, optional): List of years to extract. Only 3 seasons available. Defaults to [2019,2018,2017].

        Returns:
            season_urls (list): List of urls created

    save_player_df(df, player_id=None, verbose=True)
        Saves the player df to the data/players/subfolder
        using the player_id as filename suffix.

        Args:
            df (Frame): player's df to save
            player_id (str, optional): Player_id for filename. Defaults to None,
                which extracts it from the df..

DATA
    url = 'https://stats.nba.com/player/1628369/boxscores-traditional/'

FILE
    /Users/jamesirving/Documents/GitHub/_MY_SIDE_PROJECTS/nba_fantasy_fanduel/nba_stats.py

In [12]:
import glob
current_csvs = glob.glob('data/players/*.csv')
current_csvs

['data/players/player_id_1629662.csv',
 'data/players/player_id_2730.csv',
 'data/players/player_id_202695.csv',
 'data/players/player_id_1626220.csv',
 'data/players/player_id_203210.csv',
 'data/players/player_id_201229.csv',
 'data/players/players-index.csv',
 'data/players/player_id_1627936.csv',
 'data/players/player_id_201980.csv',
 'data/players/player_id_1628378.csv',
 'data/players/player_id_1629714.csv',
 'data/players/player_id_1626209.csv',
 'data/players/player_id_202331.csv',
 'data/players/player_id_201162.csv',
 'data/players/player_id_1629658.csv',
 'data/players/player_id_202335.csv',
 'data/players/player_id_1628396.csv',
 'data/players/player_id_1628369.csv',
 'data/players/player_id_1629671.csv',
 'data/players/player_id_1629659.csv',
 'data/players/player_id_202334.csv',
 'data/players/player_id_1626144.csv',
 'data/players/player_id_1628380.csv',
 'data/players/player_id_1628430.csv',
 'data/players/player_id_1628961.csv',
 'data/players/player_id_101150.csv',
 'data/players/player_id_2544.csv',
 'data/players/player_id_1629013.csv',
 'data/players/player_id_203918.csv',
 'data/players/player_id_1629010.csv',
 'data/players/player_id_2546.csv',
 'data/players/player_id_1629014.csv',
 'data/players/player_id_1627777.csv',
 'data/players/player_id_202355.csv',
 'data/players/player_id_1627826.csv',
 'data/players/player_id_203076.csv',
 'data/players/player_id_1629611.csv',
 'data/players/player_id_202340.csv',
 'data/players/player_id_203090.csv',
 'data/players/player_id_200765.csv',
 'data/players/player_id_203468.csv',
 'data/players/player_id_203497.csv',
 'data/players/player_id_1627746.csv',
 'data/players/player_id_1629018.csv',
 'data/players/player_id_204060.csv',
 'data/players/player_id_1629752.csv',
 'data/players/player_id_203903.csv',
 'data/players/player_id_203081.csv',
 'data/players/player_id_203484.csv',
 'data/players/player_id_1628398.csv',
 'data/players/player_id_203145.csv',
 'data/players/player_id_1626149.csv',
 'data/players/player_id_1629642.csv',
 'data/players/player_id_1626188.csv',
 'data/players/player_id_201976.csv',
 'data/players/player_id_203585.csv',
 'data/players/player_id_201580.csv',
 'data/players/player_id_202711.csv',
 'data/players/player_id_203584.csv',
 'data/players/player_id_1629650.csv',
 'data/players/player_id_201144.csv',
 'data/players/player_id_1628405.csv']

In [14]:
run_cell=False
if run_cell==True:
    fs.reload(ns)

    players_data = {}
    df['player_csv'] = np.nan
    for id_ in df['nba_id']:
        print(id_)
        current_csvs = glob.glob('data/players/*.csv')
        if str(id_) in ','.join(current_csvs):
            print(f"csv for {id_} exists, skipping...")
            continue

        player_urls = ns.make_season_urls_from_playerid(player_id=str(id_))
        df_player = ns.get_all_seasons_df(season_urls=player_urls)
        df['player_csv'] = ns.save_player_df(df_player,player_id=str(id_))
else:
    print('Skipping since run_cell==True')

Skipping since run_cell==True

### TROUBLESHOOTING ERRORS

- Could just be needed longer sleep in get_all_seasons_df (added)

In [15]:
df

              Id Position  First Name  ... Unnamed: 14 Unnamed: 15   nba_id
0    42127-15755       PF     Anthony  ...         NaN         NaN   203076
1     42127-9488       SF      LeBron  ...         NaN         NaN     2544
2    42127-14513       PF       Kawhi  ...         NaN         NaN   202695
3    42127-20848       PG      Damian  ...         NaN         NaN   203081
4    42127-40203        C        Rudy  ...         NaN         NaN   203497
5    42127-12363        C      Hassan  ...         NaN         NaN   202355
6    42127-66113       SG     Donovan  ...         NaN         NaN  1628378
7    42127-12341       SF        Paul  ...         NaN         NaN   202331
8    42127-19067       SG          CJ  ...         NaN         NaN   203468
9     42127-9508       SF     Carmelo  ...         NaN         NaN     2546
10   42127-14530       SF       Bojan  ...         NaN         NaN   202711
11   42127-59318       SF         Joe  ...         NaN         NaN   204060
12   42127-23776        C    Montrezl  ...         NaN         NaN  1626149
13    42127-9662       SG         Lou  ...         NaN         NaN   101150
14   42127-58377       PF        Kyle  ...         NaN         NaN  1628398
15   42127-12474       PG     Patrick  ...         NaN         NaN   201976
16   42127-20640       SG      Jordan  ...         NaN         NaN   203903
17    42127-9575       PG        Mike  ...         NaN         NaN   201144
18   42127-19781       SF        Kent  ...         NaN         NaN   203145
19    42127-9455       PG       Rajon  ...         NaN         NaN   200765
20    42127-9739        C      JaVale  ...         NaN         NaN   201580
21   42127-15636       SG  Kentavious  ...         NaN         NaN   203484
22   42127-18338       PF       Royce  ...         NaN         NaN  1626220
23   42127-70827        C       Ivica  ...         NaN         NaN  1627826
24    42127-9660        C      Dwight  ...         NaN         NaN     2730
25   42127-66109       PF        Skal  ...         NaN         NaN  1627746
26   42127-63124       PG    Emmanuel  ...         NaN         NaN  1626144
27    42127-9758       SG       Danny  ...         NaN         NaN   201980
28   42127-16178       SF     Maurice  ...         NaN         NaN   203090
29   42127-23981       PG        Alex  ...         NaN         NaN  1627936
30   42127-84724       PG      Landry  ...         NaN         NaN  1629013
31   42127-15744       SG      Rodney  ...         NaN         NaN   203585
32  42127-110337       SG       Talen  ...         NaN         NaN  1629659
33  42127-111492       PF        Amir  ...         NaN         NaN  1629599
34  42127-111620       PG       Nigel  ...         NaN         NaN  1628430
35  42127-110343       SF      Nassir  ...         NaN         NaN  1629642
36  42127-110355       SF     Mfiondu  ...         NaN         NaN  1629662
37   42127-63123       SF       Mario  ...         NaN         NaN  1626209
38   42127-15904       SF      Rodney  ...         NaN         NaN   203918
39  42127-117286        C       Moses  ...         NaN         NaN  1629650
40  42127-117289       PF       Juwan  ...         NaN         NaN  1629752
41   42127-15405       PF    JaMychal  ...         NaN         NaN   203210
42   42127-12334       SG       Avery  ...         NaN         NaN   202340
43   42127-80815       PF        Zach  ...         NaN         NaN  1628380
44   42127-12340       PF     Patrick  ...         NaN         NaN   202335
46   42127-80823        C        Tony  ...         NaN         NaN  1628396
47    42127-9920       PF     Anthony  ...         NaN         NaN   201229
48   42127-84677       PG      Jerome  ...         NaN         NaN  1629010
49   42127-20805       SG        Troy  ...         NaN         NaN   203584
50   42127-12362        C    DeMarcus  ...         NaN         NaN   202326
51    42127-9677       SF       Jared  ...         NaN         NaN   201162
52   42127-12365       PF          Ed  ...         NaN         NaN   202334
54   42127-84695       SG        Gary  ...         NaN         NaN  1629018
55  42127-115802       SF      Jaylen  ...         NaN         NaN  1629658
56   42127-15582       PG       Quinn  ...         NaN         NaN  1626188
57  42127-110308       SF     Jarrell  ...         NaN         NaN  1629714
58  42127-110315       SG     Terance  ...         NaN         NaN  1629611
59   42127-84717       PG    Anfernee  ...         NaN         NaN  1629014
60   42127-40561       PG     Derrick  ...         NaN         NaN  1628476
61   42127-23156       PF     Georges  ...         NaN         NaN  1627777
62   42127-84725       PF      Kostas  ...         NaN         NaN  1628961
63  42127-110324       SG        Miye  ...         NaN         NaN  1629671
64  42127-110327       PG      Justin  ...         NaN         NaN  1629625
65   42127-41597       PF   Johnathan  ...         NaN         NaN  1628405

[64 rows x 17 columns]

# BOOKMARK: STARTING TO MODEL
- Limit choices by first trying to model 1 position.
- Get csv location for each player
- Prep for XGBoost Regressor

In [36]:
##
# df.to_csv('data/122819_with_player_csvs.csv')
df_today = pd.read_csv('data/122819_with_player_csvs.csv',index_col=0)
df_today.set_index('nba_id',inplace=True)
df_today.head()

                 Id Position  ... Unnamed: 15                          player_csv
nba_id                        ...
203076  42127-15755       PF  ...         NaN  data/players/player_id_1628405.csv
2544     42127-9488       SF  ...         NaN  data/players/player_id_1628405.csv
202695  42127-14513       PF  ...         NaN  data/players/player_id_1628405.csv
203081  42127-20848       PG  ...         NaN  data/players/player_id_1628405.csv
203497  42127-40203        C  ...         NaN  data/players/player_id_1628405.csv

[5 rows x 17 columns]

In [45]:
df_today.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64 entries, 203076 to 1628405
Data columns (total 17 columns):
Id                  64 non-null object
Position            64 non-null object
First Name          64 non-null object
Nickname            64 non-null object
Last Name           64 non-null object
FPPG                64 non-null float64
Played              64 non-null int64
Salary              64 non-null int64
Game                64 non-null object
Team                64 non-null object
Opponent            64 non-null object
Injury Indicator    8 non-null object
Injury Details      8 non-null object
Tier                0 non-null float64
Unnamed: 14         0 non-null float64
Unnamed: 15         0 non-null float64
player_csv          64 non-null object
dtypes: float64(4), int64(2), object(11)
memory usage: 11.5+ KB

In [46]:
pos = df_today.groupby('Position').groups
pos.keys()

dict_keys(['C', 'PF', 'PG', 'SF', 'SG'])

In [47]:
df = df_today.loc[pos['C']]
df

                   Id Position  ... Unnamed: 15                          player_csv
nba_id                          ...
203497    42127-40203        C  ...         NaN  data/players/player_id_1628405.csv
202355    42127-12363        C  ...         NaN  data/players/player_id_1628405.csv
1626149   42127-23776        C  ...         NaN  data/players/player_id_1628405.csv
201580     42127-9739        C  ...         NaN  data/players/player_id_1628405.csv
1627826   42127-70827        C  ...         NaN  data/players/player_id_1628405.csv
2730       42127-9660        C  ...         NaN  data/players/player_id_1628405.csv
1629650  42127-117286        C  ...         NaN  data/players/player_id_1628405.csv
1628396   42127-80823        C  ...         NaN  data/players/player_id_1628405.csv
202326    42127-12362        C  ...         NaN  data/players/player_id_1628405.csv

[9 rows x 17 columns]

### Load in player's data

In [49]:
pd.set_option('display.max_rows',20)

In [48]:
PLAYER = df.iloc[0]
PLAYER

Id                                         42127-40203
Position                                             C
First Name                                        Rudy
Nickname                                   Rudy Gobert
Last Name                                       Gobert
FPPG                                           40.1655
Played                                              29
Salary                                            8700
Game                                           UTA@LAC
Team                                               UTA
Opponent                                           LAC
Injury Indicator                                   NaN
Injury Details                                     NaN
Tier                                               NaN
Unnamed: 14                                        NaN
Unnamed: 15                                        NaN
player_csv          data/players/player_id_1628405.csv
Name: 203497, dtype: object

## Preparing Data for XGBoost

In [120]:
#Player DF Dict

# display(dfx.info(),dfx.head())

## Preparing Data for XGBoost
import re
def sep_teams(row):

    import re
    row['teams'] = row['teams'].strip()
    matches = re.findall(r"([A-Z]+) .+ ([A-Z]+)", row['teams'])[0]
#     display(matches)

    row['team_1'] = matches[0]#[0]#re.findall(r'(\w*).[@|(vs)].(\w*)',row['teams'])[0][0]
    row['team_2'] = matches[-1]#[1]#re.findall(r'(\w*).[@|(vs)].(\w*)',row['teams'])[0][1]
    return row
def prep_player_nba_stats_df(PLAYER_ROW,target_col = 'total_pts'):
    ## Target column for regression is total points
    dfx = pd.read_csv(PLAYER_ROW['player_csv'])
    dfx = ns.calc_fantasy_stats(dfx)
#     dfx = dfx.set_index('date')
    
    ## Get list of fantasy points columns to keep
    fpoints_cols = [col for col in dfx.columns if 'pts' in col]

    ## Get list of original cols for fantasy points to drop
    orig_cols = [col.replace('_pts','') for col in fpoints_cols]
    orig_cols.remove('total')


    ## columns to drop for remaining column names
    drop_cols = orig_cols
    drop_cols.extend(fpoints_cols)

    ## Columns to keep
    keep_cols = fpoints_cols
    keep_cols.extend(dfx.drop(drop_cols,axis=1).columns)
    # orig_cols,fpoints_cols
    # keep_cols

    dfx = dfx[keep_cols].set_index('player_id')
    
    ## Separate Teams inton 2 features
    dfx = dfx.apply(sep_teams,axis=1)
    
    dfx.set_index('date',inplace=True)


    return dfx
dfx = prep_player_nba_stats_df(PLAYER,)    
dfx.head(3)

            3PM_pts  AST_pts  BLK_pts  FGM_pts  ...  +/-        teams  team_1  team_2
date                                            ...
2019-12-17      0.0      1.5      0.0      0.0  ...    2  LAC vs. PHX     LAC     PHX
2019-12-11      0.0      0.0      0.0      0.0  ...   -1    LAC @ TOR     LAC     TOR
2019-10-26      0.0      0.0      0.0      0.0  ...    0    LAC @ PHX     LAC     PHX

[3 rows x 26 columns]

### Concat original df_today data plus stats.nba data

- Actually not sure how to do that for modeling since would need historical columns for today's competition players' historical fanduel data.

## Clean Up Cols/Dtypes

In [121]:
dfx.isna().sum().sum()

0

In [122]:
cols_to_drop = ['Match Up','teams']
dfx = dfx.drop(columns=cols_to_drop)

obj_cols = list(dfx.select_dtypes('object').columns)
num_cols = list(dfx.select_dtypes(['int','float']).columns)

# dfx.drop(obj_cols+num_cols,axis=1).columns
display(dfx[obj_cols].head(),dfx[num_cols].head())

           W/L team_1 team_2
date
2019-12-17   W    LAC    PHX
2019-12-11   W    LAC    TOR
2019-10-26   L    LAC    PHX
2019-10-24   W    LAC    GSW
2019-04-07   L    LAC    GSW

            3PM_pts  AST_pts  BLK_pts  FGM_pts  ...  OREB  DREB  PF  +/-
date                                            ...
2019-12-17      0.0      1.5      0.0      0.0  ...     0     0   2    2
2019-12-11      0.0      0.0      0.0      0.0  ...     0     0   0   -1
2019-10-26      0.0      0.0      0.0      0.0  ...     1     0   0    0
2019-10-24      1.0      3.0      0.0      2.0  ...     0     1   1   -3
2019-04-07      0.0      1.5      0.0      8.0  ...     2     4   2    4

[5 rows x 21 columns]

In [123]:
cols_to_drop = ['Match Up','teams']
df_model = dfx.drop(columns=cols_to_drop).copy()
df_model

KeyError: "['Match Up' 'teams'] not found in axis"

In [125]:
dfx[obj_cols]

           W/L team_1 team_2
date
2019-12-17   W    LAC    PHX
2019-12-11   W    LAC    TOR
2019-10-26   L    LAC    PHX
2019-10-24   W    LAC    GSW
2019-04-07   L    LAC    GSW
...         ..    ...    ...
2018-03-17   L    DAL    BKN
2018-03-11   L    DAL    HOU
2018-02-11   L    DAL    HOU
2018-01-24   L    DAL    HOU
2017-12-14   L    DAL    GSW

[37 rows x 3 columns]

In [136]:
int_codes = df_model['W/L'].sort_values().unique()
enc_dict['W/L'].inverse_transform(int_codes)

array(['L', 'W'], dtype=object)

In [155]:
## Label Encode 
df_model = dfx.copy()
from sklearn.preprocessing import LabelEncoder
enc_dict ={}
for col in obj_cols:
    enc_dict[col] = {}
    scaler = LabelEncoder()
    
    orig_keys = df_model[col].sort_values().unique()
    
    df_model[col] = scaler.fit_transform(dfx[col])
    enc_dict[col]['scaler'] = scaler
    
    int_codes = scaler.transform(orig_keys)
    lookup_codes  = dict(zip(int_codes,orig_keys))
    
    enc_dict[col]['codex'] = lookup_codes
    
df_model

            3PM_pts  AST_pts  BLK_pts  FGM_pts  ...  PF  +/-  team_1  team_2
date                                            ...
2019-12-17      0.0      1.5      0.0      0.0  ...   2    2       1      17
2019-12-11      0.0      0.0      0.0      0.0  ...   0   -1       1      20
2019-10-26      0.0      0.0      0.0      0.0  ...   0    0       1      17
2019-10-24      1.0      3.0      0.0      2.0  ...   1   -3       1       7
2019-04-07      0.0      1.5      0.0      8.0  ...   2    4       1       7
...             ...      ...      ...      ...  ...  ..  ...     ...     ...
2018-03-17      0.0      1.5      0.0      8.0  ...   1    4       0       0
2018-03-11      0.0      0.0      0.0      0.0  ...   0    3       0       8
2018-02-11      0.0      1.5      3.0      0.0  ...   1    7       0       8
2018-01-24      0.0      0.0      0.0      4.0  ...   0    9       0       8
2017-12-14      0.0      0.0      3.0      2.0  ...   0    4       0       7

[37 rows x 24 columns]

# XGB

In [156]:
# from sklearn.model_selection import train_test_split
# train_test_split()

## Do I want to shift the total_pts field forward 1? So using last game data to predict data

In [163]:
# total_pts = df_model['total_pts'].copy()
# shifted_pts = df_model['total_pts'].copy().shift(-1).rename('shifted_pts')
# pd.concat([total_pts,shifted_pts],axis=1)

In [164]:
## using yesterday's data to predict today's points

In [166]:
# df_model['pred_points']=total_pts.diff(-1)
# df_model

In [182]:
y = df_model['total_pts'].copy()
X = df_model.drop(columns=['total_pts'])

In [183]:
# Xa =X.values
# Xa[:-2]

In [184]:
def train_test_index(X,y,n_test_games=2):
    
    if isinstance(X,pd.Series):
        X = X.values
        
    if isinstance(y,pd.Series):
        y=y.values
    X_train = X[:-n_test_games]#.copy()
    X_test = X[-n_test_games:]#.copy()
    
    y_train = y[:-n_test_games]#.copy()
    y_test = y[-n_test_games:]#.copy()
    
        

    
    return X_train,X_test,y_train,y_test
X_train,X_test,y_train,y_test = train_test_index(X,y,n_test_games=2)
X_train.shape, X_test.shape,y_train.shape,y_test.shape

((35, 23), (2, 23), (35,), (2,))

In [185]:
y_train

array([ 7.5,  2. ,  1.2,  5.2, 19.7,  7.6, 10.7,  2.7, -1. ,  3.2, 10.1,
       10.2, 16.4, 12.4, -2. ,  7.4, 13.9, 12.3, 12.6, 13.8, 12.7,  9.2,
        8.6,  2. ,  5.2,  0. , 26.7, 11.5, 47.4, 27.1,  7.8, 11.2, 14.7,
        2.4,  5.7])

In [186]:
import xgboost as xgb

model = xgb.XGBRegressor()

https://xgboost.readthedocs.io/en/latest/tutorials/param_tuning.html 

### FROM https://github.com/dmlc/xgboost/blob/master/demo/guide-python/basic_walkthrough.py
```python
import numpy as np
import scipy.sparse
import pickle
import xgboost as xgb

### simple example
# load file from text file, also binary buffer generated by xgboost
dtrain = xgb.DMatrix('../data/agaricus.txt.train')
dtest = xgb.DMatrix('../data/agaricus.txt.test')

# specify parameters via map, definition are same as c++ version
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic'}

# specify validations set to watch performance
watchlist = [(dtest, 'eval'), (dtrain, 'train')]
num_round = 2
bst = xgb.train(param, dtrain, num_round, watchlist)
```

In [217]:
params = {'learning_rate':[0.1,0.01,0.001],
          'max_depth': [6,10],
          'min_child_weight':[0,0.2,0.5,1],
         'n_estimators':[100,1000,10000]}

In [224]:
from sklearn.model_selection import RandomizedSearchCV
rand_search = RandomizedSearchCV(model,params,verbose=2)
rand_search.fit(X_train,y_train)
# rand_search.b

//anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   0.2s
[CV] n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   0.2s
[CV] n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   0.2s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01
[16:33:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01, total=   0.2s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01
[16:33:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01, total=   0.2s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01
[16:33:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.01, total=   0.2s
[CV] n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001
[16:33:06] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001, total=   2.4s
[CV] n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001
[16:33:08] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001, total=   2.5s
[CV] n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001
[16:33:10] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.5, max_depth=10, learning_rate=0.001, total=   2.2s
[CV] n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01, total=   0.0s
[CV] n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01, total=   0.0s
[CV] n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.2, max_depth=6, learning_rate=0.01, total=   0.0s
[CV] n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001, total=   0.0s
[CV] n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001, total=   0.0s
[CV] n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=100, min_child_weight=0.5, max_depth=6, learning_rate=0.001, total=   0.0s
[CV] n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   1.9s
[CV] n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:15] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   2.0s
[CV] n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001
[16:33:17] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=0.2, max_depth=6, learning_rate=0.001, total=   1.9s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001
[16:33:19] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001, total=   2.0s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001
[16:33:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001, total=   2.0s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001
[16:33:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.001, total=   2.0s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1
[16:33:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1, total=   0.1s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1
[16:33:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1, total=   0.1s
[CV] n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1
[16:33:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=0, max_depth=6, learning_rate=0.1, total=   0.1s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1
[16:33:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1, total=   0.6s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1
[16:33:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1, total=   0.6s
[CV] n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1
[16:33:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=10000, min_child_weight=1, max_depth=6, learning_rate=0.1, total=   0.6s
[CV] n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01
[16:33:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01, total=   0.2s
[CV] n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01
[16:33:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

[CV]  n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01, total=   0.2s
[CV] n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01
[16:33:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[CV]  n_estimators=1000, min_child_weight=1, max_depth=6, learning_rate=0.01, total=   0.2s
[16:33:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:   22.9s finished
//anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

RandomizedSearchCV(cv='warn', error_score='raise-deprecating',
                   estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                          colsample_bylevel=1,
                                          colsample_bynode=1,
                                          colsample_bytree=1, gamma=0,
                                          importance_type='gain',
                                          learning_rate=0.1, max_delta_step=0,
                                          max_depth=3, min_child_weight=1,
                                          missing=None, n_estimators=100,
                                          n_jobs=1, nthread=None,
                                          objective='reg:linear',
                                          rand...
                                          reg_lambda=1, scale_pos_weight=1,
                                          seed=None, silent=None, subsample=1,
                                          verbosity=1),
                   iid='warn', n_iter=10, n_jobs=None,
                   param_distributions={'learning_rate': [0.1, 0.01, 0.001],
                                        'max_depth': [6, 10],
                                        'min_child_weight': [0, 0.2, 0.5, 1],
                                        'n_estimators': [100, 1000, 10000]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [225]:
rand_search.best_params_

{'n_estimators': 10000,
 'min_child_weight': 0.2,
 'max_depth': 6,
 'learning_rate': 0.001}

In [228]:
from sklearn.model_selection import GridSearchCV
model = xgb.XGBRegressor()

params = {'learning_rate':[0.1,0.01,0.001],
          'max_depth': [6,10],
          'min_child_weight':[0,0.2,0.5,1],
         'n_estimators':[100,1000]}#,10000]}

grid_search = GridSearchCV(model,params,verbose=1)
grid_search.fit(X_train,y_train)
# rand_search.b

//anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

Fitting 3 folds for each of 48 candidates, totalling 144 fits
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:29] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:31] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

[Parallel(n_jobs=1)]: Done 144 out of 144 | elapsed:   12.7s finished
//anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

[16:36:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                    colsample_bylevel=1, colsample_bynode=1,
                                    colsample_bytree=1, gamma=0,
                                    importance_type='gain', learning_rate=0.1,
                                    max_delta_step=0, max_depth=3,
                                    min_child_weight=1, missing=None,
                                    n_estimators=100, n_jobs=1, nthread=None,
                                    objective='reg:linear', random_state=0,
                                    reg_alpha=0, reg_lambda=1,
                                    scale_pos_weight=1, seed=None, silent=None,
                                    subsample=1, verbosity=1),
             iid='warn', n_jobs=None,
             param_grid={'learning_rate': [0.1, 0.01, 0.001],
                         'max_depth': [6, 10],
                         'min_child_weight': [0, 0.2, 0.5, 1],
                         'n_estimators': [100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [230]:
grid_search.best_params_#best_estimator_

{'learning_rate': 0.01,
 'max_depth': 6,
 'min_child_weight': 0,
 'n_estimators': 1000}

In [221]:
MODEL = xgb.XGBRegressor(**rand_search.best_params_)

In [222]:
res = MODEL.fit(X_train,y_train)
res

[16:32:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.001, max_delta_step=0,
             max_depth=6, min_child_weight=0.5, missing=None,
             n_estimators=10000, n_jobs=1, nthread=None, objective='reg:linear',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [223]:
res.predict(X_test),y_test

(array([5.3488097, 5.866769 ], dtype=float32), array([8.6, 8.2]))

In [191]:
y_hat_test = trained.predict(X_test)
y_hat_train = trained.predict(X_train)

import sklearn.metrics as metrics
metrics.r2_score(y_test,y_hat_test)

-176.82445767416695

# OLD

In [99]:
# import re
# matches = re.findall(r"([A-Z]+) .+ ([A-Z]+)", dfx['teams'].iloc[0])#, row['teams'])
# len(matches[0])

In [100]:
# df_model = dfx.copy()
# df_model['Opponent'] = df_model[]

In [101]:
# ## Separate Teams inton 2 features
# import re
# def sep_teams(row):

#     import re
#     row['teams'] = row['teams'].strip()
#     matches = re.findall(r"([A-Z]+) .+ ([A-Z]+)", row['teams'])[0]
#     display(matches)

#     row['team_1'] = matches[0]#[0]#re.findall(r'(\w*).[@|(vs)].(\w*)',row['teams'])[0][0]
#     row['team_2'] = matches[-1]#[1]#re.findall(r'(\w*).[@|(vs)].(\w*)',row['teams'])[0][1]
#     return row

# dfx = dfx.apply(sep_teams,axis=1)
# dfx

In [102]:
# print('\n'.join(dfx['teams'].values))